### ISSUE TITLE
Missing sheet

### ISSUE THREAD

**Issue by Rarder44** [alexandrainst/php-xlsx-fast-editor#15]
after deleting some sheets the following error appears:

Missing XML fragment xl/worksheets/sheet2.xml!

Steps to reproduce the error:

- create an empty file
- use php-xlsx-fast-editor to edit it (read/write something)
- open the file with excel
- create a new Sheet ("Sheet2")
- delete "Sheet1"
- rename "Sheet2" to "Sheet1"
- try using php-xlsx-fast-editor again to edit the file.

**Comment by Alkarex** [comment]
Does the problem occur also without your step 2?
Could you please send a minimal piece of PHP code along with a minimal Excel file, to reproduce the issue?

**Comment by Alkarex** [comment]
Ok, I could reproduce the bug. Should be fixed with https://github.com/alexandrainst/php-xlsx-fast-editor/pull/16
Tests welcome

**Comment by Alkarex** [comment]
New release https://github.com/alexandrainst/php-xlsx-fast-editor/releases/tag/2.2.0
